org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.caching=false

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false

android.aapt2FromMavenOverride=/data/data/com.termux/files/home/Android/Sdk/build-tools/36.1.0/aapt2
